version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Pytest
          command: |
            pip3 install -U pytest --user
            ls -la
            pytest
